# DATA PREPROCESSING

In [1]:
import numpy as np
import pandas as pd

# Import Dataset

In [2]:
dataset=pd.read_csv('D:\AI(edu)\Data3.csv')

In [3]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  40.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [4]:
X=dataset.iloc[:,:-1].values
Y=dataset.iloc[:,-1].values

# MISSING VALUES

In [5]:
from sklearn.impute import SimpleImputer

In [6]:
imputer=SimpleImputer(missing_values=np.nan,strategy='mean')

In [12]:
imputer.fit(X[:,1:4])

SimpleImputer()

In [9]:
SimpleImputer()

SimpleImputer()

In [10]:
X[:,1:4]

array([[44.0, 72000.0],
       [27.0, 48000.0],
       [30.0, 54000.0],
       [38.0, 61000.0],
       [40.0, nan],
       [40.0, 58000.0],
       [nan, 52000.0],
       [48.0, 79000.0],
       [50.0, 83000.0],
       [37.0, 67000.0]], dtype=object)

In [14]:
X[:,1:4]=imputer.transform(X[:,1:4])

In [15]:
X

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 40.0, 58000.0],
       ['Spain', 39.333333333333336, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

# Encoding Categorical Values

In [16]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [17]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [18]:
X=np.array(ct.fit_transform(X))

In [19]:
X

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 40.0, 58000.0],
       [0.0, 0.0, 1.0, 39.333333333333336, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

# Dependent Variable

In [20]:
from sklearn.preprocessing import LabelEncoder

In [21]:
le=LabelEncoder()

In [22]:
Y=le.fit_transform(Y)

In [23]:
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Dataset Split


In [24]:
from sklearn.model_selection import train_test_split

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,Y,test_size=0.2,random_state=42)

# Feature Scaling

In [26]:
from sklearn.preprocessing import StandardScaler

In [27]:
sc=StandardScaler()

In [28]:
X_train[:,3:]=sc.fit_transform(X_train[:,3:])

In [31]:
X_test[:,3:]=sc.fit_transform(X_test[:,3:])

In [32]:
X_train

array([[1.0, 0.0, 0.0, 0.09361447859102087, -0.6260377781240918],
       [1.0, 0.0, 0.0, 0.9106135644762897, 1.0130429500553495],
       [1.0, 0.0, 0.0, 1.7276126503615585, 1.8325833141450703],
       [0.0, 1.0, 0.0, -1.9488832361221513, -1.0943465576039322],
       [1.0, 0.0, 0.0, -0.5191348358229307, 0.42765697570554906],
       [0.0, 1.0, 0.0, 0.09361447859102087, 0.05040823668012247],
       [0.0, 0.0, 1.0, -0.31488506435161356, -0.27480619351421154],
       [0.0, 0.0, 1.0, -0.04255203572319012, -1.3285009473438525]],
      dtype=object)

In [33]:
X_test

array([[0.0, 1.0, 0.0, 1.0, 1.0],
       [0.0, 0.0, 1.0, -1.0, -1.0]], dtype=object)