# Import Library

In [2]:
import numpy as np
import pandas as pd
from sklearn.impute import SimpleImputer

# Single Imputer

In [4]:
imp=SimpleImputer(missing_values=np.nan,strategy='mean')

In [5]:
imp.fit([[1,2],[np.nan,3],[7,6]])

SimpleImputer()

In [6]:
X=[[np.nan,2],[6,np.nan],[7,6]]

In [7]:
X=imp.transform(X)

In [8]:
X

array([[4.        , 2.        ],
       [6.        , 3.66666667],
       [7.        , 6.        ]])

# Multiple Imputer

In [10]:
from sklearn.experimental import enable_iterative_imputer
from sklearn.impute import IterativeImputer

In [11]:
imp=IterativeImputer(max_iter=10,random_state=0)

In [12]:
imp.fit([[1,2],[3,6],[4,8],[np.nan,3],[7,np.nan]])

IterativeImputer(random_state=0)

In [13]:
IterativeImputer(random_state=0)

IterativeImputer(random_state=0)

In [14]:
X_test=[[np.nan,2],[6,np.nan],[np.nan,6]]
X_test=np.round(imp.transform(X_test))

In [15]:
X_test

array([[ 1.,  2.],
       [ 6., 12.],
       [ 3.,  6.]])

# Importing Dataset

In [16]:
dataset=pd.read_csv('D:\AI(edu)\Data3.csv')

In [20]:
dataset.head(10)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  40.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [21]:
X=dataset.iloc[ : , : -1]

In [22]:
Y=dataset.iloc[ : , -1]

In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

In [30]:
ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')

In [31]:
ct

ColumnTransformer(remainder='passthrough',
                  transformers=[('encoder', OneHotEncoder(), [0])])

In [32]:
X=dataset.iloc[:,:-1]

In [33]:
X

Country   Age   Salary
0   France  44.0  72000.0
1    Spain  27.0  48000.0
2  Germany  30.0  54000.0
3    Spain  38.0  61000.0
4  Germany  40.0      NaN
5   France  40.0  58000.0
6    Spain   NaN  52000.0
7   France  48.0  79000.0
8  Germany  50.0  83000.0
9   France  37.0  67000.0

In [34]:
X=np.array(ct.fit_transform(X))

In [35]:
X

array([[1.0e+00, 0.0e+00, 0.0e+00, 4.4e+01, 7.2e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 2.7e+01, 4.8e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 0.0e+00, 1.0e+00, 3.8e+01, 6.1e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 4.0e+01,     nan],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.0e+01, 5.8e+04],
       [0.0e+00, 0.0e+00, 1.0e+00,     nan, 5.2e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 4.8e+01, 7.9e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04],
       [1.0e+00, 0.0e+00, 0.0e+00, 3.7e+01, 6.7e+04]])